config/routes.rb
PgHero::Engine.routes.draw do
  scope "(:database)", constraints: proc { |req| (PgHero.config["databases"].keys + [nil]).include?(req.params[:database]) } do
    get "space", to: "home#space"
    get "space/:relation", to: "home#relation_space", as: :relation_space
    get "index_bloat", to: "home#index_bloat"
    get "live_queries", to: "home#live_queries"
    get "queries", to: "home#queries"
    get "queries/:query_hash", to: "home#show_query", as: :show_query
    get "system", to: "home#system"
    get "cpu_usage", to: "home#cpu_usage"
    get "connection_stats", to: "home#connection_stats"
    get "replication_lag_stats", to: "home#replication_lag_stats"
    get "load_stats", to: "home#load_stats"
    get "free_space_stats", to: "home#free_space_stats"
    get "explain", to: "home#explain"
    get "tune", to: "home#tune"
    get "connections", to: "home#connections"
    get "maintenance", to: "home#maintenance"
    post "kill", to: "home#kill"
    post "kill_long_running_queries", to: "home#kill_long_running_queries"
    post "kill_all", to: "home#kill_all"
    post "enable_query_stats", to: "home#enable_query_stats"
    post "explain", to: "home#explain"
    post "reset_query_stats", to: "home#reset_query_stats"

    # legacy routes
    get "system_stats" => redirect("system")
    get "query_stats" => redirect("queries")

    root to: "home#index"
  end
end

app/controllers/pg_hero/home_controller.rb
module PgHero
  class HomeController < ActionController::Base
    layout "pg_hero/application"

    protect_from_forgery

    http_basic_authenticate_with name: PgHero.username, password: PgHero.password if PgHero.password

    before_action :check_api
    before_action :set_database
    before_action :set_query_stats_enabled
    before_action :set_show_details, only: [:index, :queries, :show_query]
    before_action :ensure_query_stats, only: [:queries]

    if PgHero.config["override_csp"]
      after_action do
        response.headers["Content-Security-Policy"] = "default-src 'self' 'unsafe-inline'"
      end
    end

    def index
      @title = "Overview"
      @extended = params[:extended]

      if @replica
        @replication_lag = @database.replication_lag
        @good_replication_lag = @replication_lag ? @replication_lag < 5 : true
      else
        @inactive_replication_slots = @database.replication_slots.select { |r| !r[:active] }
      end

      @autovacuum_queries, @long_running_queries = @database.long_running_queries.partition { |q| q[:query].starts_with?("autovacuum:") }

      connection_states = @database.connection_states
      @total_connections = connection_states.values.sum
      @idle_connections = connection_states["idle in transaction"].to_i

      @good_total_connections = @total_connections < @database.total_connections_threshold
      @good_idle_connections = @idle_connections < 100

      @transaction_id_danger = @database.transaction_id_danger(threshold: 1500000000)

      @readable_sequences, @unreadable_sequences = @database.sequences.partition { |s| s[:readable] }

      @sequence_danger = @database.sequence_danger(threshold: (params[:sequence_threshold] || 0.9).to_f, sequences: @readable_sequences)

      @indexes = @database.indexes
      @invalid_indexes = @database.invalid_indexes(indexes: @indexes)
      @invalid_constraints = @database.invalid_constraints
      @duplicate_indexes = @database.duplicate_indexes(indexes: @indexes)

      if @query_stats_enabled
        @query_stats = @database.query_stats(historical: true, start_at: 3.hours.ago)
        @slow_queries = @database.slow_queries(query_stats: @query_stats)
        set_suggested_indexes((params[:min_average_time] || 20).to_f, (params[:min_calls] || 50).to_i)
      else
        @query_stats_available = @database.query_stats_available?
        @query_stats_extension_enabled = @database.query_stats_extension_enabled? if @query_stats_available
        @suggested_indexes = []
      end

      if @extended
        @index_hit_rate = @database.index_hit_rate || 0
        @table_hit_rate = @database.table_hit_rate || 0
        @good_cache_rate = @table_hit_rate >= @database.cache_hit_rate_threshold / 100.0 && @index_hit_rate >= @database.cache_hit_rate_threshold / 100.0
        @unused_indexes = @database.unused_indexes(max_scans: 0)
      end

      @show_migrations = PgHero.show_migrations
    end

    def space
      @title = "Space"
      @days = (params[:days] || 7).to_i
      @database_size = @database.database_size
      @relation_sizes = params[:tables] ? @database.table_sizes : @database.relation_sizes
      @space_stats_enabled = @database.space_stats_enabled? && !params[:tables]
      if @space_stats_enabled
        space_growth = @database.space_growth(days: @days, relation_sizes: @relation_sizes)
        @growth_bytes_by_relation = Hash[ space_growth.map { |r| [[r[:schema], r[:relation]], r[:growth_bytes]] } ]
        case params[:sort]
        when "growth"
          @relation_sizes.sort_by! { |r| s = @growth_bytes_by_relation[[r[:schema], r[:relation]]]; [s ? 0 : 1, -s.to_i, r[:schema], r[:relation]] }
        when "name"
          @relation_sizes.sort_by! { |r| r[:relation] || r[:table] }
        end
      end

      across = params[:across].to_s.split(",")
      @unused_indexes = @database.unused_indexes(max_scans: 0, across: across)
      @unused_index_names = Set.new(@unused_indexes.map { |r| r[:index] })
      @show_migrations = PgHero.show_migrations
      @system_stats_enabled = @database.system_stats_enabled?
      @index_bloat = [] # @database.index_bloat
    end

    def relation_space
      @schema = params[:schema] || "public"
      @relation = params[:relation]
      @title = @relation
      relation_space_stats = @database.relation_space_stats(@relation, schema: @schema)
      @chart_data = [{name: "Value", data: relation_space_stats.map { |r| [r[:captured_at].change(sec: 0), r[:size_bytes].to_i] }, library: chart_library_options}]
    end

    def index_bloat
      @title = "Index Bloat"
      @index_bloat = @database.index_bloat
      @show_sql = params[:sql]
    end

    def live_queries
      @title = "Live Queries"
      @running_queries = @database.running_queries(all: true)
      @vacuum_progress = @database.vacuum_progress.index_by { |q| q[:pid] }

      if params[:state]
        @running_queries.select! { |q| q[:state] == params[:state] }
      end
    end

    def queries
      @title = "Queries"
      @sort = %w(average_time calls).include?(params[:sort]) ? params[:sort] : nil
      @min_average_time = params[:min_average_time] ? params[:min_average_time].to_i : nil
      @min_calls = params[:min_calls] ? params[:min_calls].to_i : nil

      if @historical_query_stats_enabled
        begin
          @start_at = params[:start_at] ? Time.zone.parse(params[:start_at]) : 24.hours.ago
          @end_at = Time.zone.parse(params[:end_at]) if params[:end_at]
        rescue
          @error = true
        end
      end

      @query_stats =
        if @historical_query_stats_enabled && !request.xhr?
          []
        else
          @database.query_stats(
            historical: true,
            start_at: @start_at,
            end_at: @end_at,
            sort: @sort,
            min_average_time: @min_average_time,
            min_calls: @min_calls
          )
        end

      @indexes = @database.indexes
      set_suggested_indexes

      # fix back button issue with caching
      response.headers["Cache-Control"] = "must-revalidate, no-store, no-cache, private"
      if request.xhr?
        render layout: false, partial: "queries_table", locals: {queries: @query_stats, xhr: true}
      end
    end

    def show_query
      @query_hash = params[:query_hash].to_i
      @user = params[:user].to_s
      @title = @query_hash

      stats = @database.query_stats(historical: true, query_hash: @query_hash, start_at: 24.hours.ago).find { |qs| qs[:user] == @user }
      if stats
        @query = stats[:query]
        @explainable_query = stats[:explainable_query]

        if @show_details
          query_hash_stats = @database.query_hash_stats(@query_hash, user: @user)

          @chart_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at].change(sec: 0), (r[:total_minutes] * 60 * 1000).round] }, library: chart_library_options}]
          @chart2_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at].change(sec: 0), r[:average_time].round(1)] }, library: chart_library_options}]
          @chart3_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at].change(sec: 0), r[:calls]] }, library: chart_library_options}]

          @origins = Hash[query_hash_stats.group_by { |r| r[:origin].to_s }.map { |k, v| [k, v.size] }]
          @total_count = query_hash_stats.size
        end

        @tables = PgQuery.parse(@query).tables rescue []
        @tables.sort!

        if @tables.any?
          @row_counts = Hash[@database.table_stats(table: @tables).map { |i| [i[:table], i[:estimated_rows]] }]
          @indexes_by_table = @database.indexes.group_by { |i| i[:table] }
        end
      else
        render_text "Unknown query"
      end
    end

    def system
      @title = "System"
      @periods = {
        "1 hour" => {duration: 1.hour, period: 60.seconds},
        "1 day" => {duration: 1.day, period: 10.minutes},
        "1 week" => {duration: 1.week, period: 30.minutes},
        "2 weeks" => {duration: 2.weeks, period: 1.hours}
      }
      @duration = (params[:duration] || 1.hour).to_i
      @period = (params[:period] || 60.seconds).to_i

      if @duration / @period > 1440
        render_text "Too many data points"
      elsif @period % 60 != 0
        render_text "Period must be a multiple of 60"
      end
    end

    def cpu_usage
      render json: [{name: "CPU", data: @database.cpu_usage(system_params).map { |k, v| [k, v.round] }, library: chart_library_options}]
    end

    def connection_stats
      render json: [{name: "Connections", data: @database.connection_stats(system_params), library: chart_library_options}]
    end

    def replication_lag_stats
      render json: [{name: "Lag", data: @database.replication_lag_stats(system_params), library: chart_library_options}]
    end

    def load_stats
      render json: [
        {name: "Read IOPS", data: @database.read_iops_stats(system_params).map { |k, v| [k, v.round] }, library: chart_library_options},
        {name: "Write IOPS", data: @database.write_iops_stats(system_params).map { |k, v| [k, v.round] }, library: chart_library_options}
      ]
    end

    def free_space_stats
      render json: [
        {name: "Free Space", data: @database.free_space_stats(duration: 14.days, period: 1.hour), library: chart_library_options},
      ]
    end

    def explain
      @title = "Explain"
      @query = params[:query]
      # TODO use get + token instead of post so users can share links
      # need to prevent CSRF and DoS
      if request.post? && @query
        begin
          prefix =
            case params[:commit]
            when "Analyze"
              "ANALYZE "
            when "Visualize"
              "(ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) "
            else
              ""
            end
          @explanation = @database.explain("#{prefix}#{@query}")

app/helpers/pg_hero/home_helper.rb
module PgHero
  module HomeHelper
    def pghero_pretty_ident(table, schema: nil)
      ident = table
      if schema && schema != "public"
        ident = "#{schema}.#{table}"
      end
      if ident =~ /\A[a-z0-9_]+\z/
        ident
      else
        @database.quote_ident(ident)
      end
    end

    def pghero_js_var(name, value)
      "var #{name} = #{json_escape(value.to_json(root: false))};".html_safe
    end

    def pghero_remove_index(query)
      if query[:columns]
        columns = query[:columns].map(&:to_sym)
        columns = columns.first if columns.size == 1
      end
      ret = String.new("remove_index #{query[:table].to_sym.inspect}")
      ret << ", name: #{(query[:name] || query[:index]).to_s.inspect}"
      ret << ", column: #{columns.inspect}" if columns
      ret
    end
  end
end

app/views/pg_hero/home/_live_queries_table.html.erb
<table class="table queries">
  <thead>
    <tr>
      <th style="width: 25%;">Pid</th>
      <th style="width: 25%;">Duration</th>
      <th style="width: 25%;">State</th>
      <th style="width: 25%;"></th>
    </tr>
  </thead>
  <tbody>
    <% queries.reverse.each do |query| %>
      <tr>
        <td><%= query[:pid] %></td>
        <td>
          <% sec = query[:duration_ms] / 1000.0 %>
          <% if sec < 1.minute %>
            <%= sec.round(1) %> s
          <% elsif sec < 1.day %>
            <%= Time.at(sec).utc.strftime("%H:%M:%S") %>
          <% else %>
            <% days = (sec / 1.day).floor %>
            <%= days %>d <%= Time.at(sec - days.days).utc.strftime("%H:%M:%S") %>
          <% end %>
        </td>
        <td>
          <%= query[:state] %>
          <% if vacuum_progress[query[:pid]] %>
            <br />
            <strong><%= vacuum_progress[query[:pid]][:phase] %></strong>
          <% end %>
        </td>
        <td class="text-right">
          <%= button_to "Explain", explain_path, params: {query: query[:query]}, form: {target: "_blank"}, class: "btn btn-info" %>
          <%= button_to "Kill", kill_path(pid: query[:pid]), class: "btn btn-danger" %>
        </td>
      </tr>
      <tr>
        <td colspan="6" style="border-top: none; padding: 0;">
          <%= query[:source] %> <span class="text-muted"><%= query[:user] %></span>
          <pre style="margin-top: 1em;"><code><%= query[:query] %></code></pre>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  highlightQueries();
</script>

app/views/pg_hero/home/_queries_table.html.erb
<table class="table queries-table">
  <% unless local_assigns[:xhr] %>
    <thead>
      <tr>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Total Time", {sort: nil}, data: {sort: nil}) : "Total Time" %></th>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Average Time", {sort: "average_time"}, data: {sort: "average_time"}) : "Average Time" %></th>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Calls", {sort: "calls"}, data: {sort: "calls"}) : "Calls" %></th>
      </tr>
    </thead>
  <% end %>
  <tbody id="queries">
    <% if queries.empty? %>
      <tr>
        <td colspan="3">
          <p class="queries-info text-muted">
            <% if local_assigns[:xhr] %>
              No data available for this time.
            <% else %>
              ...
            <% end %>
          </p>
        </td>
      </tr>
    <% end %>
    <% queries.each do |query| %>
      <tr>
        <td>
          <%= number_with_delimiter(query[:total_minutes].round) %> min
          <span class="percent">
            <% percent = query[:total_percent] %>
            <% if percent > 1 %>
              <%= percent.round %>%
            <% elsif percent > 0.1 %>
              <%= percent.round(1) %>%
            <% else %>
              &lt; 0.1%
            <% end %>
          </span>
        </td>
        <td>
          <%= number_with_delimiter(query[:average_time].round) %> ms
        </td>
        <td>
          <%= number_with_delimiter(query[:calls]) %>

          <span class="user">
            <% if query[:user] %>
              <%= query[:user] %>
              <% if @show_details %>
                &middot;
              <% end %>
            <% end %>
            <% if @show_details && query[:query_hash] %>
              <%= link_to "details", show_query_path(query[:query_hash], user: query[:user]), target: "_blank" %>
            <% end %>
          </span>
        </td>
      </tr>
      <tr>
        <td colspan="3" style="border-top: none; padding: 0;">
          <pre><code style="max-height: 230px; overflow: hidden;" onclick="this.style.maxHeight = 'none';"><%= query[:query] %></code></pre>
          <% if query[:query] == "<insufficient privilege>" %>
            <p class="text-muted">For security reasons, only superusers can see queries executed by other users.</p>
          <% end %>
          <% if local_assigns[:suggested_indexes] != false && (details = @suggested_indexes_by_query[query[:query]]) && (details[:index] || @debug) %>
            <%= render partial: "suggested_index", locals: {index: details[:index], details: details} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pg_hero/home/explain.html.erb
<div class="content">
  <h1>Explain</h1>

  <%= form_tag explain_path do %>
    <div class="field"><%= text_area_tag :query, @query, placeholder: "Enter a SQL query" %></div>
    <p>
      <%= submit_tag "Explain", class: "btn btn-info", style: "margin-right: 10px;" %>
      <%= submit_tag "Analyze", class: "btn btn-danger", style: "margin-right: 10px;" %>
      <%= submit_tag "Visualize", class: "btn btn-danger" %>
    </p>
  <% end %>

  <% if @explanation %>
    <% if @visualize %>
      <p>Paste the output below into the <%= link_to "Postgres Explain Visualizer", "https://tatiyants.com/pev/#/plans/new", target: "_blank" %></p>
    <% end %>
    <pre><code><%= @explanation %></code></pre>
    <% unless @visualize %>
      <p><%= link_to "See how to interpret this", "https://www.postgresql.org/docs/current/static/using-explain.html", target: "_blank" %></p>
    <% end %>
    <% if (index = @suggested_index) %>
      <%= render partial: "suggested_index", locals: {index: index, details: index[:details]} %>
    <% end %>
  <% elsif @error %>
    <div class="alert alert-danger"><%= @error %></div>
  <% end %>
</div>

app/views/pg_hero/home/live_queries.html.erb
<div class="content">
  <h1>Live Queries</h1>

  <p><%= pluralize(@running_queries.size, "query") %></p>

  <%= render partial: "live_queries_table", locals: {queries: @running_queries, vacuum_progress: @vacuum_progress} %>

  <p><%= button_to "Kill all connections", kill_all_path, class: "btn btn-danger" %></p>

  <p class="text-muted">You may need to restart your app servers afterwards.</p>
</div>

app/views/pg_hero/home/queries.html.erb
<div class="content">
  <% if @query_stats_enabled %>
    <%= button_to "Reset", reset_query_stats_path, class: "btn btn-danger", style: "float: right;" %>
  <% end %>

  <h1 style="float: left;">Queries</h1>

  <% if @historical_query_stats_enabled %>
    <%= render partial: "query_stats_slider" %>
  <% elsif @database.query_stats_table_exists? && (columns = @database.missing_query_stats_columns).any? %>
    <div style="clear: both;">
      <p>Add missing columns to re-enable historical query stats.</p>
      <pre><code><% @database.missing_query_stats_columns.each do |column| %>ALTER TABLE pghero_query_stats ADD COLUMN "<%= column %>" <%= column == "query_hash" ? "bigint" : "text" %>;
<% end %></code></pre>
      <p>Then restart the web server.</p>
    </div>
  <% end %>

  <% if @query_stats_enabled %>
    <% if @error %>
      <div class="alert alert-danger">Cannot understand start or end time.</div>
    <% elsif @query_stats.any? || @historical_query_stats_enabled %>
      <%= render partial: "queries_table", locals: {queries: @query_stats, sort_headers: true} %>
      <script>
        highlightQueries();
      </script>
    <% else %>
      <p>Stats are not available yet. Come back soon!</p>
    <% end %>
  <% else %>
    <p>Query stats are not enabled.</p>
  <% end %>
</div>

app/views/pg_hero/home/show_query.html.erb
<div class="content">
  <pre><code style="max-height: 230px; overflow: hidden;" onclick="this.style.maxHeight = 'none';"><%= @query %></code></pre>
  <script>
    highlightQueries()
  </script>

  <% if @explainable_query %>
    <p>
      <%= button_to "Explain", explain_path, params: {query: @explainable_query}, form: {target: "_blank"}, class: "btn btn-info" %>
    </p>
  <% end %>

  <% if @origins && @origins.keys.select { |k| k.length > 0 }.any? %>
    <table style="table-layout: auto;">
      <thead>
        <tr>
          <th colspan="2">
            <div style="float: right;">Approx. Time</div>
            Origin
          </th>
        </tr>
      </thead>
      <tbody>
        <% @origins.sort_by { |o, c| [-c, o.to_s] }.each do |origin, count| %>
          <tr>
            <td class="origin" style="width: 90%;">
              <% if origin.length > 0 %>
                <%= origin %>
              <% else %>
                <span class="text-muted">Unknown</span>
              <% end %>
            </td>
            <td style="text-align: right; width: 10%;">
              <% pct = (100.0 * count / @total_count).round %>
              <% if pct == 0 %>
                &lt; 1%
              <% else %>
                <%= pct %>%
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <!-- chart -->
  <% if @chart_data %>
    <h1>Total Time <small>ms</small></h1>
    <div id="chart-1" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-1", <%= json_escape(@chart_data.to_json).html_safe %>, {colors: ["#5bc0de"], legend: false, library: {tooltips: {intersect: false, mode: "index"}}})
    </script>

    <h1>Average Time <small>ms</small></h1>
    <div id="chart-2" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-2", <%= json_escape(@chart2_data.to_json).html_safe %>, {colors: ["#5bc0de"], legend: false, library: {tooltips: {intersect: false, mode: "index"}}})
    </script>

    <h1>Calls</h1>
    <div id="chart-3" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-3", <%= json_escape(@chart3_data.to_json).html_safe %>, {colors: ["#5bc0de"], legend: false, library: {tooltips: {intersect: false, mode: "index"}}})
    </script>
  <% else %>
    <p>
      Enable
      <%= link_to "historical query stats", "https://github.com/ankane/pghero", target: "_blank" %>
      to see more details
    </p>
  <% end %>

  <!-- table info -->
  <% if @tables.any? %>
    <h1>Tables</h1>
    <table>
      <thead>
        <tr>
          <th style="width: 25%;">Name</th>
          <th style="width: 25%;">Rows</th>
          <th>Indexes</th>
        </tr>
      </thead>
      <tbody>
        <% @tables.each do |table| %>
          <tr>
            <td><%= table %></td>
            <td><%= @row_counts[table] %></td>
            <td>
              <ul>
                <% @indexes_by_table[table].to_a.sort_by { |i| [i[:primary] ? 0 : 1, i[:columns]] }.each do |i3| %>
                  <li>
                    <%= i3[:columns].join(", ") %><% if i3[:using] != "btree" %>
                    <%= i3[:using].to_s.upcase %><% end %>
                    <% if i3[:primary] %> PRIMARY<% elsif i3[:unique] %> UNIQUE<% end %>
                  </li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/pg_hero/home/space.html.erb
<div class="content">
  <h1>Space</h1>

  <p>Database Size: <%= @database_size %></p>

  <% if @system_stats_enabled %>
    <div id="chart-1" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-1", <%= json_escape(free_space_stats_path.to_json).html_safe %>, {colors: ["#5bc0de"], bytes: true, library: {tooltips: {intersect: false, mode: "index"}}})
    </script>
  <% end %>

  <!--
  <% if @index_bloat.any? %>
    <p>Check out <%= link_to "index bloat", index_bloat_path %> for an easy way to reclaim space.</p>
  <% end %>
  -->

  <% if @unused_indexes.any? %>
    <p>
      <%= pluralize(@unused_indexes.size, "unused index") %>. Remove them
      <% if @show_migrations %>
        <a href="javascript: void(0);" onclick="document.getElementById('migration').style.display = 'block';">with a migration</a>
      <% end %>
      for faster writes.

      <% if @database.replicating? %>
        Check they aren’t used on replicas.
      <% end %>
    </p>

    <div id="migration" style="display: none;">
      <pre>rails generate migration remove_unused_indexes</pre>
      <p>And paste</p>
      <pre style="overflow: scroll; white-space: pre; word-break: normal;"><% @unused_indexes.sort_by { |q| [-q[:size_bytes], q[:index]] }.each do |query| %>
<%= pghero_remove_index(query) %><% end %></pre>
    </div>
  <% end %>

  <table class="table space-table">
    <thead>
      <tr>
        <th><%= link_to "Relation", {sort: "name"} %></th>
        <th style="width: 15%;"><%= link_to "Size", {} %></th>
        <% if @space_stats_enabled %>
          <th style="width: 15%;"><%= link_to "#{@days}d Growth", {sort: "growth"} %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @relation_sizes.each do |query| %>
        <tr>
          <td style="<%= query[:type] == "index" ? "font-style: italic;" : "" %>">
            <span style="word-break: break-all;">
              <% name = query[:relation] || query[:table] %>
              <% if @space_stats_enabled %>
                <%= link_to name, relation_space_path(name, schema: query[:schema]), target: "_blank", style: "color: inherit;" %>
              <% else %>
                <%= name %>
              <% end %>
            </span>
            <% if query[:schema] != "public" %>
              <span class="text-muted"><%= query[:schema] %></span>
            <% end %>
            <% if @unused_index_names.include?(query[:relation]) %>
              <span class="unused-index">UNUSED</span>
            <% end %>
          </td>
          <td><%= query[:size] %></td>
          <% if @space_stats_enabled %>
            <td>
              <% if @growth_bytes_by_relation[[query[:schema], query[:relation]]] %>
                <% if @growth_bytes_by_relation[[query[:schema], query[:relation]]] < 0 %>-<% end %><%= PgHero.pretty_size(@growth_bytes_by_relation[[query[:schema], query[:relation]]].abs) %>
              <% else %>
                <span class="text-muted">Unknown</span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pg_hero/home/system.html.erb
<div class="content">
  <p id="periods">
    <% @periods.each do |name, options| %>
      <%= link_to name, system_path(options) %>
    <% end %>
  </p>
  <% path_options = {duration: @duration, period: @period} %>

  <h1>CPU</h1>
  <div id="chart-1" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-1", <%= json_escape(cpu_usage_path(path_options).to_json).html_safe %>, {max: 100, colors: ["#5bc0de"], suffix: "%", library: {tooltips: {intersect: false, mode: "index"}}})
  </script>

  <h1>Load</h1>
  <div id="chart-2" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-2", <%= json_escape(load_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de", "#d9534f"], library: {tooltips: {intersect: false, mode: "nearest"}}})
  </script>

  <h1>Connections</h1>
  <div id="chart-3" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-3", <%= json_escape(connection_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de"], library: {tooltips: {intersect: false, mode: "index"}}})
  </script>

  <% if @database.replica? %>
    <h1>Replication Lag</h1>
    <div id="chart-4" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-4", <%= json_escape(replication_lag_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de"], library: {tooltips: {intersect: false, mode: "index"}}})
    </script>
  <% end %>
</div>